export const winnersList = [
    {
        'year': 1975,
        'series': 'Prudential World Cup',
        'final': 'Australia v West Indies',
        'venue': "Lord's, London",
        'Result': 'West Indies won by 17 runs',
        'firstInnings': 'WEST INDIES',
        'score1': '291/8(60 OVERS)',
        'secondInnings': 'AUSTRALIA',
        'score2': '274(58.4 OVERS)',
        'captain': 'Clive Llyod',
        'teams': '8',
        'total': 15,
        'minnows': 'East Africa, Sri Lanka',
        'potm': 'Clive Llyod'
    },

    {
        'year': 1979,
        'series': 'Prudential World Cup',
        'final': 'England v West Indies',
        'venue': "Lord's, London",
        'Result': 'West Indies won by 92 runs',
        'firstInnings': 'WEST INDIES',
        'score1': '286/9(60 OVERS)',
        'secondInnings': 'ENGLAND',
        'score2': '194(51 OVERS)',
        'captain': 'Clive Llyod',
        'teams': '8',
        'total': '15',
        'minnows': 'Canada, Sri Lanka',
        'potm': 'Sir Viv Richards'
    },

    {
        'year': 1983,
        'series': 'Prudential World Cup',
        'final': 'India v West Indies',
        'venue': "Lord's, London",
        'Result': 'India won by 43 runs',
        'firstInnings': 'INDIA',
        'score1': '183(54.4 OVERS)',
        'secondInnings': 'WEST INDIES',
        'score2': '140(52 OVERS)',
        'captain': 'Kapil Dev',
        'teams': '8',
        'total': '27',
        'minnows': 'Zimbabwe',
        'potm': 'Mohinder Amarnath'
    },

    {
        'year': 1987,
        'series': 'Reliance World Cup',
        'final': 'Australia v England',
        'venue': "Eden Gardens, Kolkata",
        'Result': 'Australia won by 7 runs',
        'firstInnings': 'AUSTRALIA',
        'score1': '253/5(50 OVERS)',
        'secondInnings': 'ENGLAND',
        'score2': '246/8(50 OVERS)',
        'captain': 'Allan Border',
        'teams': "8",
        'total': '27',
        'minnows': 'Zimbabwe',
        'potm': 'David Boon'
    },

    {
        'year': 1992,
        'series': 'Benson & Hedges World Cup',
        'final': 'Pakistan v England',
        'venue': "Melbourne Cricket Ground, Melbourne",
        'Result': 'Pakistan won by 22 runs',
        'firstInnings': 'PAKISTAN',
        'score1': '249/6(50 OVERS)',
        'secondInnings': 'ENGLAND',
        'score2': '227(49.2 OVERS)',
        'captain': 'Imran Khan',
        'teams': '9',
        'total': '39',
        'minnows': 'Zimbabwe',
        'potm': 'Wasim Akram'
    },

    {
        'year': 1996,
        'series': 'Wills World Cup',
        'final': 'Australia v Sri Lanka',
        'venue': "Gaddafi Stadium, Lahore",
        'Result': 'Sri Lanka won by 7 wickets',
        'firstInnings': 'AUSTRALIA',
        'score1': '241/7(50 OVERS)',
        'secondInnings': 'SRI LANKA',
        'score2': '245/3(46.2 OVERS)',
        'captain': 'Arjuna Ranatunga',
        'teams': '12',
        'total': '37',
        'minnows': 'Kenya, Netherlands, UAE',
        'potm': 'Aravinda de Silva'
    },

    {
        'year': 1999,
        'series': 'ICC Cricket World Cup',
        'final': 'Pakistan v Australia',
        'venue': "Lord's, London",
        'Result': 'Australia won by 8 wickets',
        'firstInnings': 'PAKISTAN',
        'score1': '132(39 OVERS)',
        'secondInnings': 'AUSTRALIA',
        'score2': '133/2(20.1 OVERS)',
        'captain': 'Steve Waugh',
        'teams': '12',
        'total': '42',
        'minnows': 'Kenya, Bangladesh, Scotland',
        'potm': 'Shane Warne'
    },

    {
        'year': 2003,
        'series': 'ICC Cricket World Cup',
        'final': 'Australia v India',
        'venue': "Wanderers Stadium, Johannesburg",
        'Result': 'Australia won by 125 runs',
        'firstInnings': 'AUSTRALIA',
        'score1': '359/2(50 OVERS)',
        'secondInnings': 'INDIA',
        'score2': '234(39.2 OVERS)',
        'captain': 'Ricky Ponting',
        'teams': '14',
        'total': '54',
        'minnows': 'Kenya, Canada, Namibia, Netherlands',
        'potm': 'Ricky Ponting'
    },

    {
        'year': 2007,
        'series': 'ICC Cricket World Cup',
        'final': 'Australia v Sri Lanka',
        'venue': "Kensington Oval, Bridgetown, Barbados",
        'Result': 'Australia won by 53 runs (D/L method)',
        'firstInnings': 'AUSTRALIA',
        'score1': '281/4(38 OVERS)',
        'secondInnings': 'SRI LANKA',
        'score2': '215/8(36 OVERS)',
        'captain': 'Ricky Ponting',
        'teams': '16',
        'total': '51',
        'minnows': 'Ireland, Canada, Bermuda, Netherlands, Scotland',
        'potm': 'Adam Gilchrist'
    },

    {
        'year': 2011,
        'series': 'ICC Cricket World Cup',
        'final': 'Sri Lanka v India',
        'venue': "Wankhede Stadium, Mumbai",
        'Result': 'India won by 6 wickets',
        'firstInnings': 'SRI LANKA',
        'score1': '274/6(50 OVERS)',
        'secondInnings': 'INDIA',
        'score2': '277/4(48.2 OVERS)',
        'captain': 'Mahendra Singh Dhoni',
        'teams': '14',
        'total': '49',
        'minnows': 'Kenya, Canada, Ireland, Netherlands',
        'potm': 'Mahendra Singh Dhoni'
    },

    {
        'year': 2015,
        'series': 'ICC Cricket World Cup',
        'final': 'New Zealand v Australia',
        'venue': "Melbourne Cricket Ground, Melbourne",
        'Result': 'Australia won by 7 wickets',
        'firstInnings': 'NEW ZEALAND',
        'score1': '183(45 OVERS)',
        'secondInnings': 'AUSTRALIA',
        'score2': '186/3(33.1 OVERS)',
        'captain': 'Michael Clarke',
        'teams': '14',
        'total': '49',
        'minnows': 'Scotland, UAE, Ireland, Afghanistan',
        'potm': 'James Faulkner'
    },
];